services:
  db:
    image: mysql
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: cashforce_v3
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - db-data:/var/lib/mysql

  backend:
    image: backend-image:latest
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: my-secret
      DB_NAME: cashforce_v3
    ports:
      - 3001:3001
    depends_on:
      db:
        condition: service_healthy
        restart: true        
    volumes:
      - ./backend:/app-backend

  frontend:
    image: frontend-image:latest
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - NUXT_PUBLIC_API_URL=http://localhost:3001
    volumes:
      - ./frontend:/app-frontend

volumes:
  db-data: